---
apiVersion: v1
kind: Service
metadata:
  name: rnaik26-test-redis-service-final
  labels:
    env: test
spec:
  type: ClusterIP
  selector:
    app: rnaik26-test-redis-service-app-final
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
