---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rnaik26-test-redis-pvc-final
  labels: 
    env: test 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
