version: '3'
services:
    web:
        build: .
        container_name: rahul-midterm-web
        ports:
            - 5020:5000
        volumes:
            - ./data/animals.json:/animals.json
    redis:
        image: redis:latest
        container_name: rahul-midterm-redis
        ports:
            - 6400:6379
        volumes:
            - ./config/redis.conf:/redis.conf
            - ./data/:/data
        command: [ "redis-server", "/redis.conf" ]
