---
apiVersion: v1
kind: Service
metadata:
  name: rnaik26-test-flask-service
  labels:
    username: rnaik26
    env: test
spec:
  type: ClusterIP
  selector:
    app: rnaik26-test-flask
  ports:
  - name: rnaik26-test-flask
    port: 5000
    targetPort: 5000
