---
apiVersion: v1
kind: Service
metadata:
  name: rnaik26-test-redis-service
  labels:
    username: rnaik26
    env: test
spec:
  type: ClusterIP
  selector:
    username: rnaik26
    env: test
    app: rnaik26-test-redis
  ports:
  - name: rnaik26-test-redis
    port: 6379
    targetPort: 6379
