apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnaik26-test-flask-deployment
  labels:
    app: rnaik26-test-flask
    username: rnaik26
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rnaik26-test-flask
  template:
    metadata:
      labels:
        app: rnaik26-test-flask
        username: rnaik26
        env: test
    spec:
      containers:
        - name: rnaik26-test-flask-deployment
          imagePullPolicy: Always
          image: rahulnaik401/app
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
